create table if not exists competitions (
  id bigint generated by default as identity primary key,
  sport text not null,
  country_slug text not null,
  competition_slug text not null,
  name text,
  season text,
  unique (sport, country_slug, competition_slug, season)
);

create table if not exists matches (
  id bigint primary key,
  competition_id bigint references competitions(id),
  sport text not null,
  status text,
  start_time timestamptz,
  home_team text,
  away_team text,
  home_score int,
  away_score int,
  is_live boolean default false,
  raw jsonb,
  updated_at timestamptz default now()
);

create table if not exists match_stats (
  match_id bigint primary key references matches(id) on delete cascade,
  stats jsonb,
  updated_at timestamptz default now()
);
